name: Build Main App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: nettest-build/.github/.github/workflows/dotnet-build.yml@main
    with:
      base-version: "${{ vars.BASE_VERSION }}"
      runner: 'windows-net'
