name: Build Main App

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:    
    uses: jefbarreira/nettest-build/.github/workflows/ci-generic-build-net.yml@main
    with:
      base-version: ${{ vars.BASE_VERSION }}
      runner: 'windows-net'
      repo: 'jefbarreira/nettest-main'
